TYPE=VIEW
query=select `u`.`id` AS `usuario_id`,`u`.`nome` AS `vendedor`,cast(`v`.`data_venda` as date) AS `data_venda`,count(`v`.`id`) AS `vendas_dia`,sum(`v`.`valor`) AS `faturamento_dia`,avg(`v`.`valor`) AS `ticket_medio_dia`,`m`.`valor_meta` AS `meta_diaria`,case when `m`.`valor_meta` > 0 then sum(`v`.`valor`) / `m`.`valor_meta` * 100 else 0 end AS `percentual_meta_dia`,(select count(0) from `crm_operacional`.`atendimentos` `a` where `a`.`usuario_id` = `u`.`id` and cast(`a`.`data_hora_inicio` as date) = cast(`v`.`data_venda` as date)) AS `atendimentos_dia`,(select count(0) from `crm_operacional`.`atendimentos` `a` where `a`.`usuario_id` = `u`.`id` and cast(`a`.`data_hora_inicio` as date) = cast(`v`.`data_venda` as date) and `a`.`resultado` = \'venda\') AS `atendimentos_venda_dia` from ((`crm_operacional`.`usuarios` `u` left join `crm_operacional`.`vendas` `v` on(`u`.`id` = `v`.`usuario_id` and `v`.`status` = \'concluida\' and `v`.`data_venda` >= curdate() - interval 30 day)) left join `crm_operacional`.`metas_vendedores` `m` on(`u`.`id` = `m`.`usuario_id` and `m`.`periodo` = \'diaria\' and `m`.`tipo_meta` = \'faturamento\' and `m`.`ativo` = 1 and (`m`.`data_fim` is null or `m`.`data_fim` >= curdate()))) where `u`.`perfil` in (\'vendedor\',\'gerencia\') group by `u`.`id`,`u`.`nome`,cast(`v`.`data_venda` as date),`m`.`valor_meta` order by cast(`v`.`data_venda` as date) desc,sum(`v`.`valor`) desc
md5=9e392fde85b846d0cf7d0c8ddc76228c
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=0001770728232081290
create-version=2
source=SELECT `u`.`id` AS `usuario_id`, `u`.`nome` AS `vendedor`, cast(`v`.`data_venda` as date) AS `data_venda`, count(`v`.`id`) AS `vendas_dia`, sum(`v`.`valor`) AS `faturamento_dia`, avg(`v`.`valor`) AS `ticket_medio_dia`, `m`.`valor_meta` AS `meta_diaria`, CASE WHEN `m`.`valor_meta` > 0 THEN sum(`v`.`valor`) / `m`.`valor_meta` * 100 ELSE 0 END AS `percentual_meta_dia`, (select count(0) from `atendimentos` `a` where `a`.`usuario_id` = `u`.`id` and cast(`a`.`data_hora_inicio` as date) = cast(`v`.`data_venda` as date)) AS `atendimentos_dia`, (select count(0) from `atendimentos` `a` where `a`.`usuario_id` = `u`.`id` and cast(`a`.`data_hora_inicio` as date) = cast(`v`.`data_venda` as date) and `a`.`resultado` = \'venda\') AS `atendimentos_venda_dia` FROM ((`usuarios` `u` left join `vendas` `v` on(`u`.`id` = `v`.`usuario_id` and `v`.`status` = \'concluida\' and `v`.`data_venda` >= curdate() - interval 30 day)) left join `metas_vendedores` `m` on(`u`.`id` = `m`.`usuario_id` and `m`.`periodo` = \'diaria\' and `m`.`tipo_meta` = \'faturamento\' and `m`.`ativo` = 1 and (`m`.`data_fim` is null or `m`.`data_fim` >= curdate()))) WHERE `u`.`perfil` in (\'vendedor\',\'gerencia\') GROUP BY `u`.`id`, `u`.`nome`, cast(`v`.`data_venda` as date), `m`.`valor_meta` ORDER BY cast(`v`.`data_venda` as date) DESC, sum(`v`.`valor`) DESC
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `u`.`id` AS `usuario_id`,`u`.`nome` AS `vendedor`,cast(`v`.`data_venda` as date) AS `data_venda`,count(`v`.`id`) AS `vendas_dia`,sum(`v`.`valor`) AS `faturamento_dia`,avg(`v`.`valor`) AS `ticket_medio_dia`,`m`.`valor_meta` AS `meta_diaria`,case when `m`.`valor_meta` > 0 then sum(`v`.`valor`) / `m`.`valor_meta` * 100 else 0 end AS `percentual_meta_dia`,(select count(0) from `crm_operacional`.`atendimentos` `a` where `a`.`usuario_id` = `u`.`id` and cast(`a`.`data_hora_inicio` as date) = cast(`v`.`data_venda` as date)) AS `atendimentos_dia`,(select count(0) from `crm_operacional`.`atendimentos` `a` where `a`.`usuario_id` = `u`.`id` and cast(`a`.`data_hora_inicio` as date) = cast(`v`.`data_venda` as date) and `a`.`resultado` = \'venda\') AS `atendimentos_venda_dia` from ((`crm_operacional`.`usuarios` `u` left join `crm_operacional`.`vendas` `v` on(`u`.`id` = `v`.`usuario_id` and `v`.`status` = \'concluida\' and `v`.`data_venda` >= curdate() - interval 30 day)) left join `crm_operacional`.`metas_vendedores` `m` on(`u`.`id` = `m`.`usuario_id` and `m`.`periodo` = \'diaria\' and `m`.`tipo_meta` = \'faturamento\' and `m`.`ativo` = 1 and (`m`.`data_fim` is null or `m`.`data_fim` >= curdate()))) where `u`.`perfil` in (\'vendedor\',\'gerencia\') group by `u`.`id`,`u`.`nome`,cast(`v`.`data_venda` as date),`m`.`valor_meta` order by cast(`v`.`data_venda` as date) desc,sum(`v`.`valor`) desc
mariadb-version=100432
